vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        app.path.car_images:
            uri_prefix:         '%app.path.car_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.car_images%'
